{% set name = "ionbus-utils" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9,<3.14
    - pip
    - setuptools
  run:
    - python >=3.9,<3.14
    - cryptography >=44.0
    - duckdb >=0.10
    - packaging >=23.1
    - pandas <3.0.0
    - polars
    - pyarrow >=16.0.1
    - pydantic >=2.7.2
    - pyyaml >=6.0.1
    - requests >=2.31,<3.0
    - setuptools
    - typing_extensions >=4.7.1
    - backports.strenum >=0.4.1  # [py<311]
    - eval-type-backport          # [py<310]

test:
  imports:
    - ionbus_utils

about:
  home: https://github.com/ionbus/ionbus_utils
  license: MIT
  license_family: MIT
  summary: Python utilities for logging, crypto, file ops, and more
  description: |
    A collection of Python utilities for common development tasks including
    logging, cryptography, file operations, date/time handling, caching,
    pandas operations, subprocess management, and configuration management.
